# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"b\n\rIngestRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x04 \x01(\x0c\"_\n\x0eIngestResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x16\n\x0e\x63hunks_created\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"T\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12&\n\x0c\x63hat_history\x18\x02 \x03(\x0b\x32\x10.rag.ChatMessage\x12\r\n\x05top_k\x18\x03 \x01(\x05\"\x97\x01\n\x10RetrievedContext\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x35\n\x08metadata\x18\x03 \x03(\x0b\x32#.rag.RetrievedContext.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Y\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\'\n\x08\x63ontexts\x18\x02 \x03(\x0b\x32\x15.rag.RetrievedContext\x12\x0f\n\x07sources\x18\x03 \x03(\t2q\n\nRAGService\x12\x31\n\x06Ingest\x12\x12.rag.IngestRequest\x1a\x13.rag.IngestResponse\x12\x30\n\x05Query\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEDCONTEXT_METADATAENTRY']._loaded_options = None
  _globals['_RETRIEVEDCONTEXT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INGESTREQUEST']._serialized_start=18
  _globals['_INGESTREQUEST']._serialized_end=116
  _globals['_INGESTRESPONSE']._serialized_start=118
  _globals['_INGESTRESPONSE']._serialized_end=213
  _globals['_CHATMESSAGE']._serialized_start=215
  _globals['_CHATMESSAGE']._serialized_end=259
  _globals['_QUERYREQUEST']._serialized_start=261
  _globals['_QUERYREQUEST']._serialized_end=345
  _globals['_RETRIEVEDCONTEXT']._serialized_start=348
  _globals['_RETRIEVEDCONTEXT']._serialized_end=499
  _globals['_RETRIEVEDCONTEXT_METADATAENTRY']._serialized_start=452
  _globals['_RETRIEVEDCONTEXT_METADATAENTRY']._serialized_end=499
  _globals['_QUERYRESPONSE']._serialized_start=501
  _globals['_QUERYRESPONSE']._serialized_end=590
  _globals['_RAGSERVICE']._serialized_start=592
  _globals['_RAGSERVICE']._serialized_end=705
# @@protoc_insertion_point(module_scope)
